-- Migration 025: Sync local schema with production
-- ============================================================
-- This migration adds columns and tables that exist in production
-- Supabase but were missing from the local Docker instance.
--
-- Discovered during dump-prod-to-local.ts audit (2026-06-29)
-- ============================================================

-- 1. Missing columns in existing tables
-- ----------------------------------------

-- t_evaluation: freeze/unfreeze workflow columns (prod has them)
ALTER TABLE IF EXISTS public.t_evaluation
  ADD COLUMN IF NOT EXISTS frozen_at TIMESTAMP WITHOUT TIME ZONE,
  ADD COLUMN IF NOT EXISTS unfrozen_at TIMESTAMP WITHOUT TIME ZONE,
  ADD COLUMN IF NOT EXISTS unfreeze_reason TEXT,
  ADD COLUMN IF NOT EXISTS unfreeze_authorized_by INTEGER;

-- t_professional_practices_tutor: ACTIVE flag (prod has it)
ALTER TABLE IF EXISTS public.t_professional_practices_tutor
  ADD COLUMN IF NOT EXISTS ACTIVE BOOLEAN DEFAULT true;

-- t_professional_practices: extension/withdrawal columns (prod has them, local didn't)
ALTER TABLE IF EXISTS public.t_professional_practices
  ADD COLUMN IF NOT EXISTS EXTENSION_GRANTED BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS EXTENSION_REASON TEXT,
  ADD COLUMN IF NOT EXISTS EXTENSION_GRANTED_BY INTEGER,
  ADD COLUMN IF NOT EXISTS EXTENSION_GRANTED_AT TIMESTAMP WITHOUT TIME ZONE,
  ADD COLUMN IF NOT EXISTS WITHDRAWAL_TYPE VARCHAR(50);


-- 2. Tables that exist in production but not locally
-- ----------------------------------------------------

-- t_practice_culmination: practice completion & certificate workflow
CREATE TABLE IF NOT EXISTS "t_practice_culmination" (
  "PRACTICE_ID" INTEGER NOT NULL,
  "STATUS" SMALLINT NOT NULL DEFAULT 0,
  "CERTIFICATE_NUMBER" VARCHAR(50),
  "CERTIFIED_AT" TIMESTAMP,
  "APPROVED_AT" TIMESTAMP DEFAULT NOW(),
  "APPROVED_BY" INTEGER,
  "CREATED_AT" TIMESTAMP DEFAULT NOW(),
  "UPDATED_AT" TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY ("PRACTICE_ID")
);

-- t_enrollment_field_changes: audit log for enrollment field changes
CREATE TABLE IF NOT EXISTS "t_enrollment_field_changes" (
  "CHANGE_ID" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "PROFESSIONAL_PRACTICE_ID" INTEGER NOT NULL,
  "FIELD_NAME" VARCHAR(100) NOT NULL,
  "OLD_VALUE" TEXT,
  "NEW_VALUE" TEXT,
  "CHANGED_BY" INTEGER,
  "CHANGED_AT" TIMESTAMP DEFAULT NOW()
);

-- t_system_nucleus: university nuclei/extensions
CREATE TABLE IF NOT EXISTS "t_system_nucleus" (
  "nucleus_id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "code" VARCHAR(50) NOT NULL UNIQUE,
  "name" VARCHAR(255) NOT NULL,
  "region" VARCHAR(255) NOT NULL DEFAULT '',
  "nucleus_type" VARCHAR(50) NOT NULL DEFAULT 'EXTENSIÓN',
  "phone" VARCHAR(30),
  "email" VARCHAR(255),
  "is_main" BOOLEAN NOT NULL DEFAULT FALSE,
  "status" SMALLINT NOT NULL DEFAULT 1,
  "created_at" TIMESTAMP DEFAULT NOW(),
  "updated_at" TIMESTAMP DEFAULT NOW()
);

-- t_committee_assignment: evaluation committee members
CREATE TABLE IF NOT EXISTS "t_committee_assignment" (
  "ASSIGNMENT_ID" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "PROFESSIONAL_PRACTICE_ID" INTEGER,
  "EVALUATION_ID" INTEGER,
  "USER_ID" INTEGER,
  "ROLE" VARCHAR(50) DEFAULT 'member',
  "ASSIGNED_AT" TIMESTAMP DEFAULT NOW()
);

-- t_culmination_reversals: log of culmination reversals
CREATE TABLE IF NOT EXISTS "t_culmination_reversals" (
  "REVERSAL_ID" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "PRACTICE_ID" INTEGER NOT NULL,
  "REVERSAL_REASON" TEXT,
  "REVERSED_BY" INTEGER,
  "REVERSED_AT" TIMESTAMP DEFAULT NOW()
);

-- t_nucleus_career: junction between system_nucleus and career
CREATE TABLE IF NOT EXISTS "t_nucleus_career" (
  "NUCLEUS_CAREER_ID" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "NUCLEUS_ID" INTEGER NOT NULL,
  "CAREER_ID" INTEGER NOT NULL,
  UNIQUE ("NUCLEUS_ID", "CAREER_ID")
);


-- 3. Foreign keys for new tables
-- ---------------------------------

-- t_practice_culmination FKs
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_culmination_practice') THEN
    ALTER TABLE "t_practice_culmination"
      ADD CONSTRAINT "fk_culmination_practice"
      FOREIGN KEY ("PRACTICE_ID") REFERENCES "t_professional_practices" ("PROFESSIONAL_PRACTICE_ID") ON DELETE CASCADE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_culmination_approved_by') THEN
    ALTER TABLE "t_practice_culmination"
      ADD CONSTRAINT "fk_culmination_approved_by"
      FOREIGN KEY ("APPROVED_BY") REFERENCES "t_user" ("USER_ID") ON DELETE SET NULL;
  END IF;
END $$;

-- t_enrollment_field_changes FKs
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_enrollment_field_changes_practice') THEN
    ALTER TABLE "t_enrollment_field_changes"
      ADD CONSTRAINT "fk_enrollment_field_changes_practice"
      FOREIGN KEY ("PROFESSIONAL_PRACTICE_ID") REFERENCES "t_professional_practices" ("PROFESSIONAL_PRACTICE_ID") ON DELETE CASCADE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_enrollment_field_changes_user') THEN
    ALTER TABLE "t_enrollment_field_changes"
      ADD CONSTRAINT "fk_enrollment_field_changes_user"
      FOREIGN KEY ("CHANGED_BY") REFERENCES "t_user" ("USER_ID") ON DELETE SET NULL;
  END IF;
END $$;

-- t_committee_assignment FKs
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_committee_assignment_user') THEN
    ALTER TABLE "t_committee_assignment"
      ADD CONSTRAINT "fk_committee_assignment_user"
      FOREIGN KEY ("USER_ID") REFERENCES "t_user" ("USER_ID") ON DELETE CASCADE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_committee_assignment_practice') THEN
    ALTER TABLE "t_committee_assignment"
      ADD CONSTRAINT "fk_committee_assignment_practice"
      FOREIGN KEY ("PROFESSIONAL_PRACTICE_ID") REFERENCES "t_professional_practices" ("PROFESSIONAL_PRACTICE_ID") ON DELETE CASCADE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_committee_assignment_evaluation') THEN
    ALTER TABLE "t_committee_assignment"
      ADD CONSTRAINT "fk_committee_assignment_evaluation"
      FOREIGN KEY ("EVALUATION_ID") REFERENCES "t_evaluation" ("EVALUATION_ID") ON DELETE CASCADE;
  END IF;
END $$;

-- t_culmination_reversals FKs
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_culmination_reversals_practice') THEN
    ALTER TABLE "t_culmination_reversals"
      ADD CONSTRAINT "fk_culmination_reversals_practice"
      FOREIGN KEY ("PRACTICE_ID") REFERENCES "t_professional_practices" ("PROFESSIONAL_PRACTICE_ID") ON DELETE CASCADE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_culmination_reversals_user') THEN
    ALTER TABLE "t_culmination_reversals"
      ADD CONSTRAINT "fk_culmination_reversals_user"
      FOREIGN KEY ("REVERSED_BY") REFERENCES "t_user" ("USER_ID") ON DELETE SET NULL;
  END IF;
END $$;

-- t_nucleus_career FKs
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_nucleus_career_nucleus') THEN
    ALTER TABLE "t_nucleus_career"
      ADD CONSTRAINT "fk_nucleus_career_nucleus"
      FOREIGN KEY ("NUCLEUS_ID") REFERENCES "t_system_nucleus" ("nucleus_id") ON DELETE CASCADE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_nucleus_career_career') THEN
    ALTER TABLE "t_nucleus_career"
      ADD CONSTRAINT "fk_nucleus_career_career"
      FOREIGN KEY ("CAREER_ID") REFERENCES "t_career" ("CAREER_ID") ON DELETE CASCADE;
  END IF;
END $$;

-- Indexes
CREATE INDEX IF NOT EXISTS "idx_culmination_status" ON "t_practice_culmination" ("STATUS");
CREATE INDEX IF NOT EXISTS "idx_culmination_certificate" ON "t_practice_culmination" ("CERTIFICATE_NUMBER");
CREATE INDEX IF NOT EXISTS "idx_enrollment_field_changes_practice" ON "t_enrollment_field_changes" ("PROFESSIONAL_PRACTICE_ID");
CREATE INDEX IF NOT EXISTS "idx_nucleus_career_nucleus" ON "t_nucleus_career" ("NUCLEUS_ID");
CREATE INDEX IF NOT EXISTS "idx_nucleus_career_career" ON "t_nucleus_career" ("CAREER_ID");
