--

-- Database: UNEFA Dashboard

-- Version: 2.2.0

-- Generated from Supabase public schema

--



-- ============================================================

-- TABLES

-- ============================================================



-- t_activity_logs (student activity logs for internships)

CREATE TABLE IF NOT EXISTS "t_activity_logs" (

  "ACTIVITY_LOG_ID" SERIAL NOT NULL,

  "PROFESSIONAL_PRACTICE_ID" INTEGER NOT NULL,

  "STUDENT_ID" INTEGER NOT NULL,

  "ACTIVITY_DATE" DATE NOT NULL,

  "WEEK_NUMBER" INTEGER,

  "HOURS_WORKED" NUMERIC(5,2) NOT NULL DEFAULT 0,

  "ACTIVITY_TYPE" VARCHAR(50) NOT NULL DEFAULT 'DIARIA',

  "ACTIVITY_DESCRIPTION" TEXT NOT NULL,

  "TASKS_COMPLETED" TEXT,

  "CHALLENGES" TEXT,

  "LEARNINGS" TEXT,

  "SUPERVISOR_COMMENTS" TEXT,

  "SUPERVISOR_APPROVED" BOOLEAN DEFAULT FALSE,

  "SUPERVISOR_ID" INTEGER,

  "APPROVED_AT" TIMESTAMP,

  "STATUS" SMALLINT NOT NULL DEFAULT 1,

  "CREATED_AT" TIMESTAMP NOT NULL DEFAULT NOW(),

  "UPDATED_AT" TIMESTAMP NOT NULL DEFAULT NOW(),

  "CREATED_BY" INTEGER

);



-- t_auth_log (authentication audit log)

CREATE TABLE IF NOT EXISTS "t_auth_log" (

  "ID" SERIAL NOT NULL,

  "USER_ID" INTEGER,

  "USER_CI" VARCHAR(20),

  "ACTION" VARCHAR(50) NOT NULL,

  "IP_ADDRESS" VARCHAR(45),

  "USER_AGENT" TEXT,

  "DETAILS" TEXT,

  "CREATED_AT" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP

);



-- t_backups (database backups)

CREATE TABLE IF NOT EXISTS "t_backups" (

  "id" UUID NOT NULL DEFAULT gen_random_uuid(),

  "name" VARCHAR(255) NOT NULL,

  "description" TEXT,

  "file_name" VARCHAR(255) NOT NULL,

  "size" BIGINT,

  "tables" TEXT[],

  "created_by" INTEGER,

  "data" JSONB,

  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

  "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW()

);



-- t_career (university careers)

CREATE TABLE IF NOT EXISTS "t_career" (

  "CAREER_ID" SERIAL NOT NULL,

  "CAREER_NAME" VARCHAR(255) NOT NULL,

  "CAREER_CODE" VARCHAR(255) NOT NULL,

  "MINIMUM_GRADE" NUMERIC(10,2) NOT NULL,

  "CAREER_ABBREVIATION" VARCHAR(255) NOT NULL,

  "CREATION_DATE" TIMESTAMP NOT NULL,

  "MODIF_USER_ID" INTEGER NOT NULL,

  "MODIF_USER_DATE" TIMESTAMP NOT NULL,

  "ELIM_USER_ID" INTEGER NOT NULL,

  "ELIM_USER_DATE" TIMESTAMP NOT NULL,

  "REST_USER_ID" INTEGER NOT NULL,

  "REST_USER_DATE" TIMESTAMP NOT NULL,

  "STATUS" SMALLINT NOT NULL,

  "CAREER_TYPE" VARCHAR(10) NOT NULL DEFAULT 'LARGA',

  "SEMESTER" VARCHAR(10)

);



-- t_career_internship_type (career-internship type relationship)

CREATE TABLE IF NOT EXISTS "t_career_internship_type" (

  "ID_CAREER_INTERNSHIP_TYPE_ID" SERIAL NOT NULL,

  "CAREER_ID" INTEGER NOT NULL,

  "INTERNSHIP_TYPE_ID" INTEGER NOT NULL

);



-- t_change_log (audit change log)

CREATE TABLE IF NOT EXISTS "t_change_log" (

  "CHANGE_LOG_ID" SERIAL NOT NULL,

  "DATE_TIME" TIMESTAMP NOT NULL,

  "TABLE_ID" INTEGER NOT NULL,

  "COLUMN_ID" INTEGER NOT NULL,

  "OPERATION_ID" INTEGER NOT NULL,

  "USER_ID" INTEGER NOT NULL,

  "NEW_VALUE" VARCHAR(45) NOT NULL,

  "OLD_VALUE" VARCHAR(45) NOT NULL,

  "IP_ADDRESS" VARCHAR(45) NOT NULL,

  "FORM_ID" INTEGER NOT NULL,

  "PRINT_EMAIL" VARCHAR(60) NOT NULL,

  "STATUS" SMALLINT NOT NULL

);



-- t_chat_sessions (AI chat sessions)

CREATE TABLE IF NOT EXISTS "t_chat_sessions" (

  "SESSION_ID" UUID NOT NULL DEFAULT gen_random_uuid(),

  "USER_ID" INTEGER NOT NULL,

  "TITLE" VARCHAR(100) NOT NULL DEFAULT 'Nueva conversación',

  "MESSAGES" JSONB NOT NULL DEFAULT '[]'::jsonb,

  "CREATED_AT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  "UPDATED_AT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  "STATUS" SMALLINT NOT NULL DEFAULT 1

);



-- t_columns (system metadata - table columns)

CREATE TABLE IF NOT EXISTS "t_columns" (

  "COLUMN_ID" SERIAL NOT NULL,

  "TABLE_ID" INTEGER NOT NULL,

  "COLUMN_NAME" VARCHAR(25) NOT NULL,

  "STATUS" SMALLINT NOT NULL

);



-- t_config (system configuration)

CREATE TABLE IF NOT EXISTS "t_config" (

  "CONFIG_ID" SERIAL NOT NULL,

  "RECOVERY_EMAIL" SMALLINT NOT NULL,

  "BLOCKING_DAYS" SMALLINT NOT NULL,

  "WRONG_KEY_LOCK" SMALLINT NOT NULL,

  "ATTEMPTS_KEY_BLOCK" SMALLINT NOT NULL,

  "KEY_EXPIRATION" INTEGER NOT NULL,

  "EXPIRATION_DAYS" SMALLINT NOT NULL,

  "USER_UPPERCASE" SMALLINT NOT NULL,

  "USER_LOWERCASE" SMALLINT NOT NULL,

  "USER_NUMBERS" SMALLINT NOT NULL,

  "USER_SPECIAL_CHARACTERS" SMALLINT NOT NULL,

  "USER_NUM_UPPERCASE" INTEGER NOT NULL,

  "USER_NUM_LOWERCASE" INTEGER NOT NULL,

  "USER_NUM_NUMBERS" INTEGER NOT NULL,

  "USER_NUM_SPECIAL_CHARACTERS" INTEGER NOT NULL,

  "KEY_UPPERCASE" SMALLINT NOT NULL,

  "KEY_LOWERCASE" SMALLINT NOT NULL,

  "KEY_NUMBERS" SMALLINT NOT NULL,

  "KEY_SPECIAL_CHARACTERS" SMALLINT NOT NULL,

  "KEY_NUM_UPPERCASE" INTEGER NOT NULL,

  "KEY_NUM_LOWERCASE" INTEGER NOT NULL,

  "KEY_NUM_NUMBERS" INTEGER NOT NULL,

  "KEY_NUM_SPECIAL_CHARACTERS" INTEGER NOT NULL,

  "USER_LENGTH" INTEGER NOT NULL,

  "KEY_LEGTH" INTEGER NOT NULL,

  "SECURITY_QUESTIONS" SMALLINT NOT NULL,

  "TOTAL_QUESTIONS" INTEGER NOT NULL,

  "TOTAL_PRESET_QUESTIONS" INTEGER NOT NULL,

  "TOTAL_USER_QUESTIONS" INTEGER NOT NULL,

  "TOTAL_ANSWERS" INTEGER NOT NULL

);



-- t_evaluation (internship evaluations)

CREATE TABLE IF NOT EXISTS "t_evaluation" (

  "EVALUATION_ID" SERIAL NOT NULL,

  "PROFESSIONAL_PRACTICE_ID" INTEGER NOT NULL,

  "EVALUATOR_TYPE" VARCHAR(20) NOT NULL,

  "EVALUATOR_ID" INTEGER,

  "EVALUATOR_NAME" VARCHAR(255) NOT NULL,

  "EVALUATOR_CI" VARCHAR(20),

  "TOTAL_SCORE" NUMERIC(5,2) NOT NULL,

  "OBSERVATIONS" TEXT,

  "EVALUATION_DATE" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  "COMITE_MEMBER_INDEX" INT DEFAULT NULL,

  "REGISTERED_BY" INTEGER,

  "STATUS" SMALLINT DEFAULT 1

);



-- t_evaluation_criteria (evaluation criteria definition)

CREATE TABLE IF NOT EXISTS "t_evaluation_criteria" (

  "CRITERIA_ID" SERIAL NOT NULL,

  "ITEM_NUMBER" INTEGER NOT NULL,

  "DESCRIPTION" VARCHAR(500) NOT NULL,

  "EVALUATOR_TYPE" VARCHAR(20) NOT NULL,

  "STATUS" SMALLINT DEFAULT 1

);



-- t_evaluation_detail (evaluation item scores)

CREATE TABLE IF NOT EXISTS "t_evaluation_detail" (

  "DETAIL_ID" SERIAL NOT NULL,

  "EVALUATION_ID" INTEGER NOT NULL,

  "CRITERIA_ID" INTEGER,

  "ITEM_NUMBER" INTEGER NOT NULL,

  "SCORE" NUMERIC(5,2) NOT NULL,

  "STATUS" SMALLINT DEFAULT 1

);



-- t_institution (external institutions/companies)

CREATE TABLE IF NOT EXISTS "t_institution" (

  "INSTITUTION_ID" SERIAL NOT NULL,

  "INSTITUTION_NAME" VARCHAR(255) NOT NULL,

  "INSTITUTION_ADDRESS" VARCHAR(255) NOT NULL,

  "INSTITUTION_CONTACT" VARCHAR(12) NOT NULL,

  "PRACTICE_TYPE" VARCHAR(255) NOT NULL,

  "REGION" VARCHAR(255) NOT NULL,

  "NUCLEUS" VARCHAR(255) NOT NULL,

  "EXTENSION" VARCHAR(255) NOT NULL,

  "CREATION_DATE" TIMESTAMP NOT NULL,

  "INSTITUTION_TYPE" VARCHAR(255) NOT NULL,

  "STATUS" SMALLINT NOT NULL,

  "RIF" VARCHAR(11) NOT NULL,

  "INSTITUTION_CODE" VARCHAR(25) NOT NULL

);



-- t_institution_career (institution-career relationship)

CREATE TABLE IF NOT EXISTS "t_institution_career" (

  "INSTITUTION_CAREER_ID" BIGINT NOT NULL,

  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

  "INSTITUTION_ID" INTEGER NOT NULL,

  "CAREER_ID" INTEGER NOT NULL

);



-- t_institution_internship_type (institution-internship type relationship)

CREATE TABLE IF NOT EXISTS "t_institution_internship_type" (

  "INSTITUTION_INTERNSHIP_TYPE_ID" BIGINT NOT NULL,

  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

  "INSTITUTION_ID" INTEGER NOT NULL,

  "INTERNSHIP_TYPE_ID" INTEGER NOT NULL

);



-- t_institution_manager (institution managers/contacts)

CREATE TABLE IF NOT EXISTS "t_institution_manager" (

  "MANAGER_ID" SERIAL NOT NULL,

  "person_id" INTEGER,

  "MANAGER_CI" VARCHAR(20) NOT NULL,

  "NAME" VARCHAR(255) NOT NULL,

  "SECOND_NAME" VARCHAR(255) DEFAULT NULL,

  "SURNAME" VARCHAR(255) NOT NULL,

  "SECOND_SURNAME" VARCHAR(255) DEFAULT NULL,

  "CONTACT_PHONE" VARCHAR(20) NOT NULL,

  "EMAIL" VARCHAR(255) NOT NULL,

  "CREATION_DATE" TIMESTAMP NOT NULL,

  "STATUS" SMALLINT NOT NULL,

  "INSTITUTION_ID" INTEGER,

  "cargo" VARCHAR(100),

  "TITLE" VARCHAR(100) DEFAULT NULL

);



-- t_institution_manager_institution (manager-institution relationship)

CREATE TABLE IF NOT EXISTS "t_institution_manager_institution" (

  "INSTITUTION_MANAGER_INSTITUTION_ID" BIGINT NOT NULL,

  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

  "MANAGER_ID" INTEGER NOT NULL,

  "INSTITUTION_ID" INTEGER NOT NULL,

  "cargo" VARCHAR(100)

);



-- t_internship_type (types of internships)

CREATE TABLE IF NOT EXISTS "t_internship_type" (

  "INTERNSHIP_TYPE_ID" SERIAL NOT NULL,

  "NAME" VARCHAR(40) NOT NULL,

  "PRIORITY" SMALLINT NOT NULL,

  "CREATION_DATE" TIMESTAMP NOT NULL,

  "STATUS" SMALLINT NOT NULL,

  "HOURS_REQUIRED" INTEGER DEFAULT 360

);



-- t_internships_period (academic periods)

CREATE TABLE IF NOT EXISTS "t_internships_period" (

  "PERIOD_ID" SERIAL NOT NULL,

  "START_DATE" DATE NOT NULL,

  "END_DATE" DATE NOT NULL,

  "ENROLLMENT_GRACE_DAYS" SMALLINT NOT NULL DEFAULT 21,

  "EVALUATION_GRACE_DAYS" SMALLINT NOT NULL DEFAULT 10,

  "CREATION_DATE" TIMESTAMP NOT NULL,

  "DESCRIPTION" VARCHAR(45) NOT NULL,

  "PERIOD_STATUS" VARCHAR(45) NOT NULL,

  "STATUS" SMALLINT NOT NULL,

  "T_INTERNSHIPS_CODE" VARCHAR(8) NOT NULL

);



-- t_period_type_dates (per-type date overrides for academic periods)

CREATE TABLE IF NOT EXISTS "t_period_type_dates" (

  "ID" SERIAL NOT NULL,

  "PERIOD_ID" INTEGER NOT NULL,

  "INTERNSHIP_TYPE_ID" INTEGER NOT NULL,

  "START_DATE" DATE,

  "END_DATE" DATE,

  "CREATION_DATE" TIMESTAMP DEFAULT NOW(),

  "MODIF_USER_ID" INTEGER,

  "MODIF_USER_DATE" TIMESTAMP,

  UNIQUE ("PERIOD_ID", "INTERNSHIP_TYPE_ID")

);



-- t_academic_config (global academic defaults — grace periods)

CREATE TABLE IF NOT EXISTS "t_academic_config" (

  "CONFIG_ID" SMALLINT PRIMARY KEY DEFAULT 1,

  "DEFAULT_ENROLLMENT_GRACE_DAYS" SMALLINT NOT NULL DEFAULT 21,

  "DEFAULT_EVALUATION_GRACE_DAYS" SMALLINT NOT NULL DEFAULT 10,

  "UPDATED_AT" TIMESTAMP NOT NULL DEFAULT NOW(),

  "UPDATED_BY" INTEGER 

);









-- t_key_history (user key/password history)

CREATE TABLE IF NOT EXISTS "t_key_history" (

  "KEY_HISTORY_ID" SERIAL NOT NULL,

  "USER_KEY_ID" INTEGER NOT NULL,

  "USER_ID" INTEGER NOT NULL,

  "END_DATE" VARCHAR(45) NOT NULL,

  "STATUS" SMALLINT NOT NULL

);



-- t_landing_config (landing page configuration)

CREATE TABLE IF NOT EXISTS "t_landing_config" (

  "config_id" SERIAL NOT NULL,

  "config_key" VARCHAR(100) NOT NULL,

  "config_value" JSONB,

  "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  "updated_by" VARCHAR(50) DEFAULT 'system'

);



-- t_list (system list definitions)

CREATE TABLE IF NOT EXISTS "t_list" (

  "LIST_ID" SERIAL NOT NULL,

  "NAME" VARCHAR(40) NOT NULL,

  "CREATION_DATE" TIMESTAMP NOT NULL,

  "MODIF_USER_ID" INTEGER NOT NULL,

  "MODIF_USER_DATE" TIMESTAMP NOT NULL,

  "ELIM_USER_ID" INTEGER NOT NULL,

  "ELIM_USER_DATE" TIMESTAMP NOT NULL,

  "REST_USER_ID" INTEGER NOT NULL,

  "REST_USER_DATE" TIMESTAMP NOT NULL,

  "STATUS" SMALLINT NOT NULL

);



-- t_notifications (user notifications)

CREATE TABLE IF NOT EXISTS "t_notifications" (

  "NOTIFICATION_ID" SERIAL NOT NULL,

  "USER_ID" INTEGER NOT NULL,

  "TYPE" VARCHAR(50) NOT NULL,

  "TITLE" VARCHAR(255) NOT NULL,

  "MESSAGE" TEXT NOT NULL,

  "READ" BOOLEAN DEFAULT FALSE,

  "READ_AT" TIMESTAMP,

  "DATA" JSONB,

  "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);



-- t_operation (system metadata - operations)

CREATE TABLE IF NOT EXISTS "t_operation" (

  "OPERATION_ID" SERIAL NOT NULL,

  "ACTION" VARCHAR(45) NOT NULL,

  "DESCRIPTION" TEXT,

  "STATUS" SMALLINT NOT NULL

);



-- t_password_history (password change history)

CREATE TABLE IF NOT EXISTS "t_password_history" (

  "HISTORY_ID" SERIAL NOT NULL,

  "USER_ID" INTEGER NOT NULL,

  "KEY" TEXT NOT NULL,

  "CREATION_DATE" TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);



-- t_permissions (system permissions)

CREATE TABLE IF NOT EXISTS "t_permissions" (

  "PERMISSIONS_ID" SERIAL NOT NULL,

  "NAME" VARCHAR(30) NOT NULL,

  "MODULE" VARCHAR(30) NOT NULL,

  "DESCRIPTION" TEXT,

  "MODIF_USER_ID" INTEGER NOT NULL,

  "MODIF_USER_DATE" TIMESTAMP NOT NULL,

  "ELIM_USER_ID" INTEGER NOT NULL,

  "ELIM_USER_DATE" TIMESTAMP NOT NULL,

  "REST_USER_ID" INTEGER NOT NULL,

  "REST_USER_DATE" TIMESTAMP NOT NULL,

  "STATUS" SMALLINT NOT NULL

);



ALTER TABLE "t_permissions" ADD CONSTRAINT "uq_permissions_name" UNIQUE ("NAME");



-- t_persons (centralized personal data — migration 001)

CREATE TABLE IF NOT EXISTS "t_persons" (

    "person_id"        SERIAL PRIMARY KEY,

    "ci"               VARCHAR(10) NOT NULL UNIQUE,

    "first_name"       VARCHAR(255) NOT NULL,

    "middle_name"      VARCHAR(255),

    "last_name"        VARCHAR(255) NOT NULL,

    "second_last_name" VARCHAR(255),

    "email"            VARCHAR(255) NOT NULL,

    "phone"            VARCHAR(15),

    "gender"           VARCHAR(10),

    "birthdate"        DATE,

    "address"          VARCHAR(255),

    "marital_status"   VARCHAR(45),

    "status"           SMALLINT DEFAULT 1,

    "created_at"       TIMESTAMP DEFAULT NOW(),

    "updated_at"       TIMESTAMP DEFAULT NOW()

);



CREATE INDEX IF NOT EXISTS "idx_persons_ci" ON "t_persons"("ci");

CREATE INDEX IF NOT EXISTS "idx_persons_names" ON "t_persons"("first_name", "last_name");

CREATE INDEX IF NOT EXISTS "idx_persons_email" ON "t_persons"("email");

CREATE INDEX IF NOT EXISTS "idx_persons_status" ON "t_persons"("status");



-- t_practice_visits (supervision visits to internship sites)

CREATE TABLE IF NOT EXISTS "t_practice_visits" (

  "VISIT_ID" SERIAL NOT NULL,

  "PROFESSIONAL_PRACTICE_ID" INTEGER NOT NULL,

  "TUTOR_ID" INTEGER NOT NULL,

  "VISIT_DATE" TIMESTAMP NOT NULL DEFAULT NOW(),

  "VISIT_TYPE" VARCHAR(50) NOT NULL DEFAULT 'PRESENCIAL',

  "HOURS_WORKED" NUMERIC(5,2) DEFAULT 0,

  "ACTIVITIES_PERFORMED" TEXT,

  "OBSERVATIONS" TEXT,

  "RECOMMENDATIONS" TEXT,

  "STATUS" SMALLINT NOT NULL DEFAULT 1,

  "CREATED_AT" TIMESTAMP NOT NULL DEFAULT NOW(),

  "UPDATED_AT" TIMESTAMP NOT NULL DEFAULT NOW(),

  "CREATED_BY" INTEGER,

  "VISIT_CASE" VARCHAR(50) DEFAULT 'SEGUIMIENTO_REGULAR'

);



-- t_preset_questions (preset security questions)

CREATE TABLE IF NOT EXISTS "t_preset_questions" (

  "PRESET_QUESTION_ID" SERIAL NOT NULL,

  "DESCRIPTION" VARCHAR(255) NOT NULL,

  "ANSWER" VARCHAR(255) NOT NULL,

  "MODIF_USER_ID" INTEGER NOT NULL,

  "MODIF_USER_DATE" TIMESTAMP NOT NULL,

  "ELIM_USER_ID" INTEGER NOT NULL,

  "ELIM_USER_DATE" TIMESTAMP NOT NULL,

  "REST_USER_ID" INTEGER NOT NULL,

  "REST_USER_DATE" TIMESTAMP NOT NULL,

  "STATUS" SMALLINT NOT NULL

);



-- t_professional_practices (student internship registrations)

CREATE TABLE IF NOT EXISTS "t_professional_practices" (

  "PROFESSIONAL_PRACTICE_ID" SERIAL NOT NULL,

  "START_DATE" DATE NOT NULL,

  "END_DATE" DATE NOT NULL,

  "REPORT_TITLE" VARCHAR(255) NOT NULL,

  "REGISTRATION_DATE" TIMESTAMP NOT NULL,

  "CREATION_DATE" TIMESTAMP NOT NULL,

  "GRADE" NUMERIC(5,2) NOT NULL,

  "TRANSFER" SMALLINT NOT NULL,

  "TOUR" VARCHAR(255) NOT NULL,

  "PERIOD_ID" INTEGER NOT NULL,

  "INSTITUTION_ID" INTEGER,

  "STUDENTS_ID" INTEGER NOT NULL,

  "STATUS" SMALLINT NOT NULL,

  "MANAGER_ID" INTEGER,

  "OBSERVATION" VARCHAR(255) NOT NULL,

  "ENROLLMENT" VARCHAR(255) NOT NULL,

  "INTERNSHIP_STATUS" INTEGER NOT NULL,

  "INTERNSHIP_TYPE_ID" INTEGER NOT NULL,

  "PRACTICES_STATUS" INTEGER NOT NULL,

  "EVALUATION_STATUS" VARCHAR(20) DEFAULT 'pending',

  "SEMESTER" VARCHAR(255) NOT NULL,

  "SECTION" VARCHAR(255) NOT NULL,

  "REGIME" VARCHAR(255) NOT NULL,

  "CAREER_ID" INTEGER NOT NULL

);



-- t_professional_practices_tutor (practice-tutor assignment)

CREATE TABLE IF NOT EXISTS "t_professional_practices_tutor" (

  "PROFESSIONAL_PRACTICES_TUTOR_ID" SERIAL NOT NULL,

  "TUTOR_ID" INTEGER NOT NULL,

  "PROFESSIONAL_PRACTICE_ID" INTEGER NOT NULL,

  "TUTOR_TYPE" VARCHAR(45) NOT NULL

);



-- t_recovery_tokens (password recovery tokens)

CREATE TABLE IF NOT EXISTS "t_recovery_tokens" (

  "TOKEN_ID" SERIAL NOT NULL,

  "USER_ID" INTEGER NOT NULL,

  "TOKEN" VARCHAR(255) NOT NULL,

  "EXPIRATION_DATE" TIMESTAMP NOT NULL,

  "STATUS" SMALLINT DEFAULT 1,

  "CREATION_DATE" TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);



-- t_request_types (types of student requests)

CREATE TABLE IF NOT EXISTS "t_request_types" (

  "REQUEST_TYPE_ID" SERIAL NOT NULL,

  "NAME" VARCHAR(100) NOT NULL,

  "DESCRIPTION" TEXT,

  "IS_ACTIVE" SMALLINT NOT NULL DEFAULT 1,

  "CREATION_DATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  "MODIF_USER_ID" INTEGER NOT NULL DEFAULT 0,

  "MODIF_USER_DATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  "ELIM_USER_ID" INTEGER NOT NULL DEFAULT 0,

  "ELIM_USER_DATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  "REST_USER_ID" INTEGER NOT NULL DEFAULT 0,

  "REST_USER_DATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  "STATUS" SMALLINT NOT NULL DEFAULT 1,

  "IS_REASSIGNMENT" SMALLINT DEFAULT 0,

  "CATEGORY" VARCHAR(50) DEFAULT 'GENERAL'

);



-- t_roles (system roles)

CREATE TABLE IF NOT EXISTS "t_roles" (

  "ID_ROLS" SERIAL NOT NULL,

  "NAME" VARCHAR(30) NOT NULL,

  "DESCRIPTION" TEXT,

  "MODIF_USER_ID" INTEGER NOT NULL,

  "MODIF_USER_DATE" TIMESTAMP NOT NULL,

  "ELIM_USER_ID" INTEGER NOT NULL,

  "ELIM_USER_DATE" TIMESTAMP NOT NULL,

  "REST_USER_ID" INTEGER NOT NULL,

  "REST_USER_DATE" TIMESTAMP NOT NULL,

  "STATUS" SMALLINT NOT NULL

);



-- t_roles_permissions (role-permission assignment)

CREATE TABLE IF NOT EXISTS "t_roles_permissions" (

  "ROLES_ID" SERIAL NOT NULL,

  "PERMISSIONS_ID" INTEGER NOT NULL

);



-- t_security_questions (user security question answers)

CREATE TABLE IF NOT EXISTS "t_security_questions" (

  "SECURITY_QUESTIONS_ID" SERIAL NOT NULL,

  "USER_ID" INTEGER NOT NULL,

  "PRESET_QUESTION_ID" INTEGER NOT NULL,

  "ANSWER" TEXT,

  "CUSTOM_QUESTION" TEXT

);



-- t_session (user login sessions)

CREATE TABLE IF NOT EXISTS "t_session" (

  "SESSION_ID" SERIAL NOT NULL,

  "USER_ID" INTEGER NOT NULL,

  "LOGIN_TIME" TIMESTAMP NOT NULL,

  "MODIF_USER_ID" INTEGER NOT NULL,

  "MODIF_USER_DATE" TIMESTAMP NOT NULL,

  "ELIM_USER_ID" INTEGER NOT NULL,

  "ELIM_USER_DATE" TIMESTAMP NOT NULL,

  "REST_USER_ID" INTEGER NOT NULL,

  "REST_USER_DATE" TIMESTAMP NOT NULL,

  "STATUS" SMALLINT NOT NULL

);



-- t_session_attempts (failed login attempts)

CREATE TABLE IF NOT EXISTS "t_session_attempts" (

  "ATTEMPT_ID" SERIAL NOT NULL,

  "ATTEMPT_TIME" TIMESTAMP NOT NULL,

  "USER_ID" INTEGER NOT NULL,

  "ACTION" SMALLINT NOT NULL,

  "MODIF_USER_ID" INTEGER NOT NULL,

  "MODIF_USER_DATE" TIMESTAMP NOT NULL,

  "ELIM_USER_ID" INTEGER NOT NULL,

  "ELIM_USER_DATE" TIMESTAMP NOT NULL,

  "REST_USER_ID" INTEGER NOT NULL,

  "REST_USER_DATE" TIMESTAMP NOT NULL,

  "STATUS" SMALLINT NOT NULL

);



-- t_session_history (session login/logout history)

CREATE TABLE IF NOT EXISTS "t_session_history" (

  "SESSION_HISTORY_ID" SERIAL NOT NULL,

  "SESSION_ID" INTEGER NOT NULL,

  "USER_ID" INTEGER NOT NULL,

  "LOGIN_TIME" TIMESTAMP NOT NULL,

  "LOGOUT_TIME" TIMESTAMP NOT NULL,

  "STATUS" SMALLINT NOT NULL

);



-- t_student_documents (student uploaded documents)

CREATE TABLE IF NOT EXISTS "t_student_documents" (

  "DOCUMENT_ID" SERIAL NOT NULL,

  "STUDENT_ID" INTEGER NOT NULL,

  "DOCUMENT_TYPE" VARCHAR(50) NOT NULL,

  "TITLE" VARCHAR(255) NOT NULL,

  "DESCRIPTION" TEXT,

  "FILE_NAME" VARCHAR(255) NOT NULL,

  "FILE_PATH" VARCHAR(500) NOT NULL,

  "FILE_SIZE" INTEGER,

  "FILE_TYPE" VARCHAR(100),

  "STATUS" VARCHAR(20) NOT NULL DEFAULT 'pending',

  "REJECTION_REASON" TEXT,

  "UPLOADED_AT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  "REVIEWED_AT" TIMESTAMP,

  "REVIEWED_BY" INTEGER,

  "CREATION_DATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  "MODIF_USER_ID" INTEGER NOT NULL DEFAULT 0,

  "MODIF_USER_DATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  "STATUS_TABLE" SMALLINT NOT NULL DEFAULT 1

);



-- t_student_requests (student requests/complaints)

CREATE TABLE IF NOT EXISTS "t_student_requests" (

  "REQUEST_ID" SERIAL NOT NULL,

  "STUDENT_ID" INTEGER NOT NULL,

  "REQUEST_TYPE_ID" INTEGER NOT NULL,

  "SUBJECT" VARCHAR(255) NOT NULL,

  "DESCRIPTION" TEXT NOT NULL,

  "STATUS" VARCHAR(20) NOT NULL DEFAULT 'pending',

  "RESPONSE" TEXT,

  "PROCESSED_BY" INTEGER,

  "PROCESSED_AT" TIMESTAMP,

  "CREATION_DATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  "MODIF_USER_ID" INTEGER NOT NULL DEFAULT 0,

  "MODIF_USER_DATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  "ELIM_USER_ID" INTEGER NOT NULL DEFAULT 0,

  "ELIM_USER_DATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  "REST_USER_ID" INTEGER NOT NULL DEFAULT 0,

  "REST_USER_DATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  "STATUS_TABLE" SMALLINT NOT NULL DEFAULT 1,

  "REASSIGNMENT_DATA" JSONB,

  "IS_REASSIGNMENT" SMALLINT DEFAULT 0,

  "PREVIOUS_TUTOR_ID" INTEGER,

  "PREVIOUS_INSTITUTION_ID" INTEGER,

  "PREVIOUS_CAREER_ID" INTEGER

);



-- t_students (student records)

CREATE TABLE IF NOT EXISTS "t_students" (

  "STUDENTS_ID" SERIAL NOT NULL,

  "person_id" INTEGER,

  "STUDENTS_CI" VARCHAR(10) NOT NULL,

  "NAME" VARCHAR(255) NOT NULL,

  "SECOND_NAME" VARCHAR(255) DEFAULT NULL,

  "SURNAME" VARCHAR(255) NOT NULL,

  "SECOND_SURNAME" VARCHAR(255) DEFAULT NULL,

  "GENDER" CHAR(10) NOT NULL,

  "BIRTHDATE" DATE NOT NULL,

  "CONTACT_PHONE" VARCHAR(15) NOT NULL,

  "EMAIL" VARCHAR(255) NOT NULL,

  "ADDRESS" VARCHAR(255) NOT NULL,

  "MARITAL_STATUS" VARCHAR(45) NOT NULL,

  "STUDENT_TYPE" VARCHAR(45) NOT NULL,

  "MILITARY_RANK" VARCHAR(45) DEFAULT NULL,

  "EMPLOYMENT" VARCHAR(2) NOT NULL,

  "STATUS" SMALLINT NOT NULL,

  "REGISTRATION_DATE" TIMESTAMP,

  "USER_ID" INTEGER

);



-- t_tables (system metadata - tables registry)

CREATE TABLE IF NOT EXISTS "t_tables" (

  "TABLE_ID" SERIAL NOT NULL,

  "NAME" VARCHAR(25) NOT NULL,

  "DESCRIPTION" TEXT,

  "PHYSICAL_NAME" VARCHAR(25) NOT NULL,

  "LOG" SMALLINT NOT NULL,

  "STATUS" SMALLINT NOT NULL

);



-- t_tutor_career (tutor-career relationship)

CREATE TABLE IF NOT EXISTS "t_tutor_career" (

  "TUTOR_CAREER_ID" BIGINT NOT NULL,

  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

  "TUTOR_ID" INTEGER NOT NULL,

  "CAREER_ID" INTEGER NOT NULL

);



-- t_tutors (academic tutors)

CREATE TABLE IF NOT EXISTS "t_tutors" (

  "TUTOR_ID" SERIAL NOT NULL,

  "person_id" INTEGER,

  "TUTOR_CI" VARCHAR(10) NOT NULL,

  "NAME" VARCHAR(255) NOT NULL,

  "SECOND_NAME" VARCHAR(255) DEFAULT NULL,

  "SURNAME" VARCHAR(255) NOT NULL,

  "SECOND_SURNAME" VARCHAR(255) DEFAULT NULL,

  "CONTACT_PHONE" VARCHAR(12) NOT NULL,

  "GENDER" VARCHAR(45) NOT NULL,

  "EMAIL" VARCHAR(255) NOT NULL,

  "PROFESSION" VARCHAR(255) NOT NULL,

  "CONDITION" VARCHAR(45) NOT NULL,

  "DEDICATION" VARCHAR(45) NOT NULL,

  "CATEGORY" VARCHAR(45) NOT NULL,

  "CREATION_DATE" TIMESTAMP NOT NULL,

  "STATUS" SMALLINT NOT NULL,

  "USER_ID" INTEGER,

  "TITULO" VARCHAR(50) DEFAULT NULL

);



-- t_user (system users)

CREATE TABLE IF NOT EXISTS "t_user" (

  "USER_ID" SERIAL NOT NULL,

  "person_id" INTEGER,

  "USER" VARCHAR(255) NOT NULL,

  "USER_CI" VARCHAR(10) NOT NULL,

  "NAME" VARCHAR(255) NOT NULL,

  "SECOND_NAME" VARCHAR(255) DEFAULT NULL,

  "SURNAME" VARCHAR(255) NOT NULL,

  "SECOND_SURNAME" VARCHAR(255) DEFAULT NULL,

  "EMAIL" VARCHAR(255) NOT NULL,

  "PHONE_NUMBER" VARCHAR(12) DEFAULT NULL,

  "CREATION_DATE" TIMESTAMP NOT NULL,

  "LOGIN" SMALLINT NOT NULL,

  "TERMS_CONDITIONS" VARCHAR(45) NOT NULL,

  "STATUS_SESSION" SMALLINT NOT NULL,

  "STATUS" SMALLINT NOT NULL,

  "FAILED_ATTEMPTS" INTEGER DEFAULT 0,

  "LOCK_DATE" TIMESTAMP WITH TIME ZONE,

  "FORCE_PASSWORD_CHANGE" BOOLEAN DEFAULT FALSE

);



-- t_user_key (user passwords/keys)

CREATE TABLE IF NOT EXISTS "t_user_key" (

  "USER_KEY_ID" SERIAL NOT NULL,

  "USER_ID" INTEGER NOT NULL,

  "KEY" VARCHAR(255) NOT NULL,

  "START_DATE" TIMESTAMP NOT NULL,

  "END_DATE" TIMESTAMP NOT NULL,

  "MODIF_USER_ID" INTEGER NOT NULL,

  "MODIF_USER_DATE" TIMESTAMP NOT NULL,

  "ELIM_USER_ID" INTEGER NOT NULL,

  "ELIM_USER_DATE" TIMESTAMP NOT NULL,

  "REST_USER_ID" INTEGER NOT NULL,

  "REST_USER_DATE" TIMESTAMP NOT NULL,

  "STATUS" SMALLINT NOT NULL,

  "IS_TEMPORARY" BOOLEAN DEFAULT FALSE

);



-- t_user_questions (user security questions)

CREATE TABLE IF NOT EXISTS "t_user_questions" (

  "USER_QUESTION_ID" SERIAL NOT NULL,

  "USER_ID" INTEGER NOT NULL,

  "QUESTION_TYPE" VARCHAR(20) NOT NULL DEFAULT 'PRESET',

  "PRESET_QUESTION_ID" INTEGER,

  "CUSTOM_QUESTION" VARCHAR(255),

  "ANSWER" VARCHAR(255) NOT NULL,

  "ORDER_NUM" SMALLINT NOT NULL DEFAULT 1,

  "CREATED_AT" TIMESTAMP NOT NULL DEFAULT NOW(),

  "UPDATED_AT" TIMESTAMP NOT NULL DEFAULT NOW(),

  "STATUS" SMALLINT NOT NULL DEFAULT 1

);



-- t_user_roles (user-role assignment)

CREATE TABLE IF NOT EXISTS "t_user_roles" (

  "ID_USER" INTEGER NOT NULL,

  "ID_ROLES" INTEGER NOT NULL

);



-- t_user_theme (user theme preferences)

CREATE TABLE IF NOT EXISTS "t_user_theme" (

  "USER_THEME_ID" SERIAL NOT NULL,

  "USER_ID" INTEGER NOT NULL,

  "BRAND_COLOR" VARCHAR(20) NOT NULL DEFAULT 'blue',

  "CREATION_DATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  "MODIF_USER_ID" INTEGER NOT NULL DEFAULT 0,

  "MODIF_USER_DATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  "ELIM_USER_ID" INTEGER NOT NULL DEFAULT 0,

  "ELIM_USER_DATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  "REST_USER_ID" INTEGER NOT NULL DEFAULT 0,

  "REST_USER_DATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  "STATUS" SMALLINT NOT NULL DEFAULT 1

);



-- t_value_list (system list values)

CREATE TABLE IF NOT EXISTS "t_value_list" (

  "VALUE_LIST_ID" SERIAL NOT NULL,

  "NAME" VARCHAR(45) NOT NULL,

  "ABBREVIATION" VARCHAR(8) DEFAULT NULL,

  "LIST_ID" INTEGER NOT NULL,

  "CREATION_DATE" TIMESTAMP NOT NULL,

  "MODIF_USER_ID" INTEGER NOT NULL,

  "MODIF_USER_DATE" TIMESTAMP NOT NULL,

  "ELIM_USER_ID" INTEGER NOT NULL,

  "ELIM_USER_DATE" TIMESTAMP NOT NULL,

  "REST_USER_ID" INTEGER NOT NULL,

  "REST_USER_DATE" TIMESTAMP NOT NULL,

  "STATUS" SMALLINT NOT NULL

);



-- t_visit (legacy visit tracking - superseded by t_practice_visits)

CREATE TABLE IF NOT EXISTS "t_visit" (

  "VISIT_ID" SERIAL NOT NULL,

  "VISIT_DATE" DATE NOT NULL,

  "NOTE" VARCHAR(255) DEFAULT NULL,

  "REQUESTED_ACTIVITY" VARCHAR(45) NOT NULL,

  "CARRIED_ACTIVITY" VARCHAR(45) NOT NULL,

  "STATUS" SMALLINT NOT NULL,

  "TUTOR_ID" INTEGER NOT NULL,

  "PROFESSIONAL_PRACTICE_ID" INTEGER NOT NULL

);



-- t_practice_culmination (practice culmination and certification)

CREATE TABLE IF NOT EXISTS "t_practice_culmination" (

  "PRACTICE_ID" INTEGER NOT NULL,

  "STATUS" SMALLINT NOT NULL DEFAULT 0,

  "CERTIFICATE_NUMBER" VARCHAR(50),

  "CERTIFIED_AT" TIMESTAMP,

  "APPROVED_AT" TIMESTAMP DEFAULT NOW(),

  "APPROVED_BY" INTEGER,

  "CREATED_AT" TIMESTAMP DEFAULT NOW(),

  "UPDATED_AT" TIMESTAMP DEFAULT NOW()

);



-- ============================================================

-- PRIMARY KEYS

-- ============================================================



ALTER TABLE "t_activity_logs" ADD PRIMARY KEY ("ACTIVITY_LOG_ID");

ALTER TABLE "t_auth_log" ADD PRIMARY KEY ("ID");

ALTER TABLE "t_backups" ADD PRIMARY KEY ("id");

ALTER TABLE "t_career" ADD PRIMARY KEY ("CAREER_ID");

ALTER TABLE "t_career_internship_type" ADD PRIMARY KEY ("ID_CAREER_INTERNSHIP_TYPE_ID");

ALTER TABLE "t_change_log" ADD PRIMARY KEY ("CHANGE_LOG_ID");

ALTER TABLE "t_chat_sessions" ADD PRIMARY KEY ("SESSION_ID");

ALTER TABLE "t_columns" ADD PRIMARY KEY ("COLUMN_ID");

ALTER TABLE "t_config" ADD PRIMARY KEY ("CONFIG_ID");

ALTER TABLE "t_evaluation" ADD PRIMARY KEY ("EVALUATION_ID");

ALTER TABLE "t_evaluation_criteria" ADD PRIMARY KEY ("CRITERIA_ID");

ALTER TABLE "t_evaluation_detail" ADD PRIMARY KEY ("DETAIL_ID");

ALTER TABLE "t_institution" ADD PRIMARY KEY ("INSTITUTION_ID");

ALTER TABLE "t_institution_career" ADD PRIMARY KEY ("INSTITUTION_CAREER_ID");

ALTER TABLE "t_institution_internship_type" ADD PRIMARY KEY ("INSTITUTION_INTERNSHIP_TYPE_ID");

ALTER TABLE "t_institution_manager" ADD PRIMARY KEY ("MANAGER_ID");

ALTER TABLE "t_institution_manager_institution" ADD PRIMARY KEY ("INSTITUTION_MANAGER_INSTITUTION_ID");

ALTER TABLE "t_internship_type" ADD PRIMARY KEY ("INTERNSHIP_TYPE_ID");

ALTER TABLE "t_internships_period" ADD PRIMARY KEY ("PERIOD_ID");

ALTER TABLE "t_period_type_dates" ADD PRIMARY KEY ("ID");

ALTER TABLE "t_key_history" ADD PRIMARY KEY ("KEY_HISTORY_ID");

ALTER TABLE "t_landing_config" ADD PRIMARY KEY ("config_id");

ALTER TABLE "t_list" ADD PRIMARY KEY ("LIST_ID");

ALTER TABLE "t_notifications" ADD PRIMARY KEY ("NOTIFICATION_ID");

ALTER TABLE "t_operation" ADD PRIMARY KEY ("OPERATION_ID");

ALTER TABLE "t_password_history" ADD PRIMARY KEY ("HISTORY_ID");

ALTER TABLE "t_permissions" ADD PRIMARY KEY ("PERMISSIONS_ID");

ALTER TABLE "t_practice_visits" ADD PRIMARY KEY ("VISIT_ID");

ALTER TABLE "t_preset_questions" ADD PRIMARY KEY ("PRESET_QUESTION_ID");

ALTER TABLE "t_practice_culmination" ADD PRIMARY KEY ("PRACTICE_ID");

ALTER TABLE "t_professional_practices" ADD PRIMARY KEY ("PROFESSIONAL_PRACTICE_ID");

ALTER TABLE "t_professional_practices_tutor" ADD PRIMARY KEY ("PROFESSIONAL_PRACTICES_TUTOR_ID");

ALTER TABLE "t_recovery_tokens" ADD PRIMARY KEY ("TOKEN_ID");

ALTER TABLE "t_request_types" ADD PRIMARY KEY ("REQUEST_TYPE_ID");

ALTER TABLE "t_roles" ADD PRIMARY KEY ("ID_ROLS");

ALTER TABLE "t_roles_permissions" ADD PRIMARY KEY ("ROLES_ID", "PERMISSIONS_ID");

ALTER TABLE "t_security_questions" ADD PRIMARY KEY ("SECURITY_QUESTIONS_ID");

ALTER TABLE "t_session" ADD PRIMARY KEY ("SESSION_ID", "USER_ID");

ALTER TABLE "t_session_attempts" ADD PRIMARY KEY ("ATTEMPT_ID");

ALTER TABLE "t_session_history" ADD PRIMARY KEY ("SESSION_HISTORY_ID");

ALTER TABLE "t_student_documents" ADD PRIMARY KEY ("DOCUMENT_ID");

ALTER TABLE "t_student_requests" ADD PRIMARY KEY ("REQUEST_ID");

ALTER TABLE "t_students" ADD PRIMARY KEY ("STUDENTS_ID");

ALTER TABLE "t_tables" ADD PRIMARY KEY ("TABLE_ID");

ALTER TABLE "t_tutor_career" ADD PRIMARY KEY ("TUTOR_CAREER_ID");

ALTER TABLE "t_tutors" ADD PRIMARY KEY ("TUTOR_ID");

ALTER TABLE "t_user" ADD PRIMARY KEY ("USER_ID");

ALTER TABLE "t_user_key" ADD PRIMARY KEY ("USER_KEY_ID", "USER_ID");

ALTER TABLE "t_user_questions" ADD PRIMARY KEY ("USER_QUESTION_ID");

ALTER TABLE "t_user_roles" ADD PRIMARY KEY ("ID_USER", "ID_ROLES");

ALTER TABLE "t_user_theme" ADD PRIMARY KEY ("USER_THEME_ID");

ALTER TABLE "t_value_list" ADD PRIMARY KEY ("VALUE_LIST_ID");

ALTER TABLE "t_visit" ADD PRIMARY KEY ("VISIT_ID");



-- ============================================================

-- UNIQUE CONSTRAINTS

-- ============================================================



ALTER TABLE "t_career" ADD UNIQUE ("CAREER_CODE");

ALTER TABLE "t_institution" ADD UNIQUE ("RIF");

ALTER TABLE "t_institution_manager" ADD UNIQUE ("MANAGER_CI");

ALTER TABLE "t_landing_config" ADD UNIQUE ("config_key");

ALTER TABLE "t_students" ADD UNIQUE ("STUDENTS_CI");

ALTER TABLE "t_tutors" ADD UNIQUE ("TUTOR_CI");

ALTER TABLE "t_user" ADD UNIQUE ("USER_CI");

ALTER TABLE "t_user_theme" ADD UNIQUE ("USER_ID");



-- ============================================================

-- FOREIGN KEYS

-- ============================================================



-- t_activity_logs

ALTER TABLE "t_activity_logs" ADD CONSTRAINT "fk_activity_logs_practice" FOREIGN KEY ("PROFESSIONAL_PRACTICE_ID") REFERENCES "t_professional_practices" ("PROFESSIONAL_PRACTICE_ID") ON DELETE CASCADE;

ALTER TABLE "t_activity_logs" ADD CONSTRAINT "fk_activity_logs_student" FOREIGN KEY ("STUDENT_ID") REFERENCES "t_students" ("STUDENTS_ID") ON DELETE CASCADE;



-- t_auth_log

ALTER TABLE "t_auth_log" ADD CONSTRAINT "fk_auth_log_user" FOREIGN KEY ("USER_ID") REFERENCES "t_user" ("USER_ID");



-- t_backups

ALTER TABLE "t_backups" ADD CONSTRAINT "fk_backups_user" FOREIGN KEY ("created_by") REFERENCES "t_user" ("USER_ID");



-- t_career_internship_type

ALTER TABLE "t_career_internship_type" ADD CONSTRAINT "fk_cit_career" FOREIGN KEY ("CAREER_ID") REFERENCES "t_career" ("CAREER_ID") ON DELETE NO ACTION;

ALTER TABLE "t_career_internship_type" ADD CONSTRAINT "fk_cit_internship_type" FOREIGN KEY ("INTERNSHIP_TYPE_ID") REFERENCES "t_internship_type" ("INTERNSHIP_TYPE_ID") ON DELETE NO ACTION;



-- t_change_log

ALTER TABLE "t_change_log" ADD CONSTRAINT "fk_change_log_columns" FOREIGN KEY ("COLUMN_ID") REFERENCES "t_columns" ("COLUMN_ID");

ALTER TABLE "t_change_log" ADD CONSTRAINT "fk_change_log_operation" FOREIGN KEY ("OPERATION_ID") REFERENCES "t_operation" ("OPERATION_ID");

ALTER TABLE "t_change_log" ADD CONSTRAINT "fk_change_log_tables" FOREIGN KEY ("TABLE_ID") REFERENCES "t_tables" ("TABLE_ID");

ALTER TABLE "t_change_log" ADD CONSTRAINT "fk_change_log_user" FOREIGN KEY ("USER_ID") REFERENCES "t_user" ("USER_ID");



-- t_chat_sessions

ALTER TABLE "t_chat_sessions" ADD CONSTRAINT "fk_chat_session_user" FOREIGN KEY ("USER_ID") REFERENCES "t_user" ("USER_ID");



-- t_columns

ALTER TABLE "t_columns" ADD CONSTRAINT "fk_columns_tables" FOREIGN KEY ("TABLE_ID") REFERENCES "t_tables" ("TABLE_ID");



-- t_evaluation

ALTER TABLE "t_evaluation" ADD CONSTRAINT "fk_evaluation_practice" FOREIGN KEY ("PROFESSIONAL_PRACTICE_ID") REFERENCES "t_professional_practices" ("PROFESSIONAL_PRACTICE_ID");

ALTER TABLE "t_evaluation" ADD CONSTRAINT "fk_evaluation_registered_by" FOREIGN KEY ("REGISTERED_BY") REFERENCES "t_user" ("USER_ID");



-- t_evaluation_detail

ALTER TABLE "t_evaluation_detail" ADD CONSTRAINT "fk_evaluation_detail_evaluation" FOREIGN KEY ("EVALUATION_ID") REFERENCES "t_evaluation" ("EVALUATION_ID") ON DELETE CASCADE;

ALTER TABLE "t_evaluation_detail" ADD CONSTRAINT "fk_evaluation_detail_criteria" FOREIGN KEY ("CRITERIA_ID") REFERENCES "t_evaluation_criteria" ("CRITERIA_ID");



-- t_institution_career

ALTER TABLE "t_institution_career" ADD CONSTRAINT "fk_inst_career_institution" FOREIGN KEY ("INSTITUTION_ID") REFERENCES "t_institution" ("INSTITUTION_ID");

ALTER TABLE "t_institution_career" ADD CONSTRAINT "fk_inst_career_career" FOREIGN KEY ("CAREER_ID") REFERENCES "t_career" ("CAREER_ID");



-- t_institution_internship_type

ALTER TABLE "t_institution_internship_type" ADD CONSTRAINT "fk_inst_inter_type_institution" FOREIGN KEY ("INSTITUTION_ID") REFERENCES "t_institution" ("INSTITUTION_ID");

ALTER TABLE "t_institution_internship_type" ADD CONSTRAINT "fk_inst_inter_type_type" FOREIGN KEY ("INTERNSHIP_TYPE_ID") REFERENCES "t_internship_type" ("INTERNSHIP_TYPE_ID");



-- t_institution_manager

ALTER TABLE "t_institution_manager" ADD CONSTRAINT "fk_manager_institution" FOREIGN KEY ("INSTITUTION_ID") REFERENCES "t_institution" ("INSTITUTION_ID") ON DELETE SET NULL;



-- t_institution_manager_institution

ALTER TABLE "t_institution_manager_institution" ADD CONSTRAINT "fk_manager_inst_manager" FOREIGN KEY ("MANAGER_ID") REFERENCES "t_institution_manager" ("MANAGER_ID");

ALTER TABLE "t_institution_manager_institution" ADD CONSTRAINT "fk_manager_inst_institution" FOREIGN KEY ("INSTITUTION_ID") REFERENCES "t_institution" ("INSTITUTION_ID");



-- t_key_history

ALTER TABLE "t_key_history" ADD CONSTRAINT "fk_key_history_user_key" FOREIGN KEY ("USER_KEY_ID", "USER_ID") REFERENCES "t_user_key" ("USER_KEY_ID", "USER_ID");



-- t_notifications

ALTER TABLE "t_notifications" ADD CONSTRAINT "fk_notification_user" FOREIGN KEY ("USER_ID") REFERENCES "t_user" ("USER_ID") ON DELETE CASCADE;



-- t_password_history

ALTER TABLE "t_password_history" ADD CONSTRAINT "fk_password_history_user" FOREIGN KEY ("USER_ID") REFERENCES "t_user" ("USER_ID");



-- t_practice_visits

ALTER TABLE "t_practice_visits" ADD CONSTRAINT "fk_practice_visits_practice" FOREIGN KEY ("PROFESSIONAL_PRACTICE_ID") REFERENCES "t_professional_practices" ("PROFESSIONAL_PRACTICE_ID");

ALTER TABLE "t_practice_visits" ADD CONSTRAINT "fk_practice_visits_tutor" FOREIGN KEY ("TUTOR_ID") REFERENCES "t_tutors" ("TUTOR_ID");



-- t_professional_practices

ALTER TABLE "t_professional_practices" ADD CONSTRAINT "fk_pp_period" FOREIGN KEY ("PERIOD_ID") REFERENCES "t_internships_period" ("PERIOD_ID");

ALTER TABLE "t_professional_practices" ADD CONSTRAINT "fk_pp_institution" FOREIGN KEY ("INSTITUTION_ID") REFERENCES "t_institution" ("INSTITUTION_ID");

ALTER TABLE "t_professional_practices" ADD CONSTRAINT "fk_pp_student" FOREIGN KEY ("STUDENTS_ID") REFERENCES "t_students" ("STUDENTS_ID");

ALTER TABLE "t_professional_practices" ADD CONSTRAINT "fk_pp_manager" FOREIGN KEY ("MANAGER_ID") REFERENCES "t_institution_manager" ("MANAGER_ID");

ALTER TABLE "t_professional_practices" ADD CONSTRAINT "fk_pp_internship_type" FOREIGN KEY ("INTERNSHIP_TYPE_ID") REFERENCES "t_internship_type" ("INTERNSHIP_TYPE_ID");

ALTER TABLE "t_professional_practices" ADD CONSTRAINT "fk_pp_career" FOREIGN KEY ("CAREER_ID") REFERENCES "t_career" ("CAREER_ID");



-- t_period_type_dates

ALTER TABLE "t_period_type_dates" ADD CONSTRAINT "fk_ptd_period" FOREIGN KEY ("PERIOD_ID") REFERENCES "t_internships_period" ("PERIOD_ID");

ALTER TABLE "t_period_type_dates" ADD CONSTRAINT "fk_ptd_internship_type" FOREIGN KEY ("INTERNSHIP_TYPE_ID") REFERENCES "t_internship_type" ("INTERNSHIP_TYPE_ID");



-- t_professional_practices_tutor

ALTER TABLE "t_professional_practices_tutor" ADD CONSTRAINT "fk_ppt_tutor" FOREIGN KEY ("TUTOR_ID") REFERENCES "t_tutors" ("TUTOR_ID");

ALTER TABLE "t_professional_practices_tutor" ADD CONSTRAINT "fk_ppt_practice" FOREIGN KEY ("PROFESSIONAL_PRACTICE_ID") REFERENCES "t_professional_practices" ("PROFESSIONAL_PRACTICE_ID");



-- t_recovery_tokens

ALTER TABLE "t_recovery_tokens" ADD CONSTRAINT "fk_recovery_user" FOREIGN KEY ("USER_ID") REFERENCES "t_user" ("USER_ID");



-- t_roles_permissions

ALTER TABLE "t_roles_permissions" ADD CONSTRAINT "fk_rp_role" FOREIGN KEY ("ROLES_ID") REFERENCES "t_roles" ("ID_ROLS");

ALTER TABLE "t_roles_permissions" ADD CONSTRAINT "fk_rp_permission" FOREIGN KEY ("PERMISSIONS_ID") REFERENCES "t_permissions" ("PERMISSIONS_ID");



-- t_security_questions

ALTER TABLE "t_security_questions" ADD CONSTRAINT "fk_sq_user" FOREIGN KEY ("USER_ID") REFERENCES "t_user" ("USER_ID");

ALTER TABLE "t_security_questions" ADD CONSTRAINT "fk_sq_preset" FOREIGN KEY ("PRESET_QUESTION_ID") REFERENCES "t_preset_questions" ("PRESET_QUESTION_ID");



-- t_session

ALTER TABLE "t_session" ADD CONSTRAINT "fk_session_user" FOREIGN KEY ("USER_ID") REFERENCES "t_user" ("USER_ID");



-- t_session_attempts

ALTER TABLE "t_session_attempts" ADD CONSTRAINT "fk_session_attempts_user" FOREIGN KEY ("USER_ID") REFERENCES "t_user" ("USER_ID");



-- t_session_history

ALTER TABLE "t_session_history" ADD CONSTRAINT "fk_session_history_session" FOREIGN KEY ("SESSION_ID", "USER_ID") REFERENCES "t_session" ("SESSION_ID", "USER_ID");



-- t_student_documents

ALTER TABLE "t_student_documents" ADD CONSTRAINT "fk_document_student" FOREIGN KEY ("STUDENT_ID") REFERENCES "t_students" ("STUDENTS_ID") ON DELETE CASCADE;

ALTER TABLE "t_student_documents" ADD CONSTRAINT "fk_document_reviewer" FOREIGN KEY ("REVIEWED_BY") REFERENCES "t_user" ("USER_ID") ON DELETE SET NULL;



-- t_student_requests

ALTER TABLE "t_student_requests" ADD CONSTRAINT "fk_request_student" FOREIGN KEY ("STUDENT_ID") REFERENCES "t_students" ("STUDENTS_ID") ON DELETE CASCADE;

ALTER TABLE "t_student_requests" ADD CONSTRAINT "fk_request_type" FOREIGN KEY ("REQUEST_TYPE_ID") REFERENCES "t_request_types" ("REQUEST_TYPE_ID") ON DELETE RESTRICT;



-- t_tutor_career

ALTER TABLE "t_tutor_career" ADD CONSTRAINT "fk_tutor_career_tutor" FOREIGN KEY ("TUTOR_ID") REFERENCES "t_tutors" ("TUTOR_ID");

ALTER TABLE "t_tutor_career" ADD CONSTRAINT "fk_tutor_career_career" FOREIGN KEY ("CAREER_ID") REFERENCES "t_career" ("CAREER_ID");



-- t_user_key

ALTER TABLE "t_user_key" ADD CONSTRAINT "fk_user_key_user" FOREIGN KEY ("USER_ID") REFERENCES "t_user" ("USER_ID");



-- t_user_questions

ALTER TABLE "t_user_questions" ADD CONSTRAINT "fk_user_questions_user" FOREIGN KEY ("USER_ID") REFERENCES "t_user" ("USER_ID") ON DELETE CASCADE;

ALTER TABLE "t_user_questions" ADD CONSTRAINT "fk_user_questions_preset" FOREIGN KEY ("PRESET_QUESTION_ID") REFERENCES "t_preset_questions" ("PRESET_QUESTION_ID") ON DELETE SET NULL;



-- t_user_roles

ALTER TABLE "t_user_roles" ADD CONSTRAINT "fk_user_roles_user" FOREIGN KEY ("ID_USER") REFERENCES "t_user" ("USER_ID");

ALTER TABLE "t_user_roles" ADD CONSTRAINT "fk_user_roles_role" FOREIGN KEY ("ID_ROLES") REFERENCES "t_roles" ("ID_ROLS");



-- t_user_theme

ALTER TABLE "t_user_theme" ADD CONSTRAINT "fk_user_theme_user" FOREIGN KEY ("USER_ID") REFERENCES "t_user" ("USER_ID") ON DELETE CASCADE;



-- t_value_list

ALTER TABLE "t_value_list" ADD CONSTRAINT "fk_value_list_list" FOREIGN KEY ("LIST_ID") REFERENCES "t_list" ("LIST_ID");



-- t_visit

ALTER TABLE "t_visit" ADD CONSTRAINT "fk_visit_practice" FOREIGN KEY ("PROFESSIONAL_PRACTICE_ID") REFERENCES "t_professional_practices" ("PROFESSIONAL_PRACTICE_ID");

ALTER TABLE "t_visit" ADD CONSTRAINT "fk_visit_tutor" FOREIGN KEY ("TUTOR_ID") REFERENCES "t_tutors" ("TUTOR_ID");



-- t_practice_culmination

ALTER TABLE "t_practice_culmination" ADD CONSTRAINT "fk_culmination_practice" FOREIGN KEY ("PRACTICE_ID") REFERENCES "t_professional_practices" ("PROFESSIONAL_PRACTICE_ID") ON DELETE CASCADE;

ALTER TABLE "t_practice_culmination" ADD CONSTRAINT "fk_culmination_approved_by" FOREIGN KEY ("APPROVED_BY") REFERENCES "t_user" ("USER_ID") ON DELETE SET NULL;



-- Check constraint para STATUS en t_practice_culmination

ALTER TABLE "t_practice_culmination" ADD CONSTRAINT "chk_culmination_status" CHECK ("STATUS" IN (0, 1, 2));



-- ============================================================

-- CHECK CONSTRAINTS

-- ============================================================



ALTER TABLE "t_notifications" ADD CONSTRAINT "chk_notification_type" CHECK ("TYPE" IN (

  'pre_enrollment', 'enrollment', 'tracking', 'tracking_visit',

  'user_management', 'reminder', 'system', 'approval'

));

ALTER TABLE "t_evaluation" ADD CONSTRAINT "chk_comite_member_index" CHECK (

  ("EVALUATOR_TYPE" = 'COMITE' AND "COMITE_MEMBER_INDEX" BETWEEN 1 AND 3)

  OR

  ("EVALUATOR_TYPE" != 'COMITE' AND "COMITE_MEMBER_INDEX" IS NULL)

);

ALTER TABLE "t_evaluation_detail" ADD CONSTRAINT "chk_score_range" CHECK ("SCORE" >= 1 AND "SCORE" <= 10);



-- ============================================================

-- INDEXES

-- ============================================================



-- t_students

CREATE INDEX IF NOT EXISTS "idx_students_ci" ON "t_students" ("STUDENTS_CI");

CREATE INDEX IF NOT EXISTS "idx_students_names" ON "t_students" ("NAME", "SURNAME");

CREATE INDEX IF NOT EXISTS "idx_students_status" ON "t_students" ("STATUS");



-- t_institution

CREATE INDEX IF NOT EXISTS "idx_institutions_name" ON "t_institution" ("INSTITUTION_NAME");

CREATE INDEX IF NOT EXISTS "idx_institutions_rif" ON "t_institution" ("RIF");

CREATE INDEX IF NOT EXISTS "idx_institutions_status" ON "t_institution" ("STATUS");

CREATE INDEX IF NOT EXISTS "idx_institution_code" ON "t_institution" ("INSTITUTION_CODE");



-- t_career

CREATE INDEX IF NOT EXISTS "idx_careers_name" ON "t_career" ("CAREER_NAME");

CREATE INDEX IF NOT EXISTS "idx_careers_status" ON "t_career" ("STATUS");



-- t_professional_practices

CREATE INDEX IF NOT EXISTS "idx_practices_reg_date" ON "t_professional_practices" ("REGISTRATION_DATE");

CREATE INDEX IF NOT EXISTS "idx_practices_status" ON "t_professional_practices" ("STATUS");

CREATE INDEX IF NOT EXISTS "idx_practices_student_id" ON "t_professional_practices" ("STUDENTS_ID");

CREATE INDEX IF NOT EXISTS "idx_practices_institution_id" ON "t_professional_practices" ("INSTITUTION_ID");



-- Partial unique index: un estudiante solo puede tener UNA práctica activa

-- (PRE_INSCRITO o INSCRITO) a la vez. Previene race conditions y duplicados

-- incluso si la validación en app-level falla.

CREATE UNIQUE INDEX IF NOT EXISTS "uq_active_practice_per_student"

  ON "t_professional_practices" ("STUDENTS_ID")

  WHERE "PRACTICES_STATUS" IN (1, 2) AND "STATUS" = 1;



-- t_career_internship_type

CREATE INDEX IF NOT EXISTS "idx_career_internship_type_career_id" ON "t_career_internship_type" ("CAREER_ID");



-- t_professional_practices_tutor

CREATE INDEX IF NOT EXISTS "idx_pp_tutor_practice_id" ON "t_professional_practices_tutor" ("PROFESSIONAL_PRACTICE_ID");



-- t_practice_visits

CREATE INDEX IF NOT EXISTS "idx_visits_practice_id" ON "t_practice_visits" ("PROFESSIONAL_PRACTICE_ID");

CREATE INDEX IF NOT EXISTS "idx_visits_tutor_id" ON "t_practice_visits" ("TUTOR_ID");

CREATE INDEX IF NOT EXISTS "idx_visits_date" ON "t_practice_visits" ("VISIT_DATE");

CREATE INDEX IF NOT EXISTS "idx_visits_status" ON "t_practice_visits" ("STATUS");

CREATE INDEX IF NOT EXISTS "idx_visits_case" ON "t_practice_visits" ("VISIT_CASE");



-- t_user_questions

CREATE INDEX IF NOT EXISTS "idx_user_questions_user" ON "t_user_questions" ("USER_ID");

CREATE INDEX IF NOT EXISTS "idx_user_questions_preset" ON "t_user_questions" ("PRESET_QUESTION_ID");



-- t_institution_career

CREATE INDEX IF NOT EXISTS "idx_institution_career_institution" ON "t_institution_career" ("INSTITUTION_ID");

CREATE INDEX IF NOT EXISTS "idx_institution_career_career" ON "t_institution_career" ("CAREER_ID");



-- t_backups

CREATE INDEX IF NOT EXISTS "idx_backups_created_at" ON "t_backups" ("created_at" DESC);



-- t_evaluation

CREATE INDEX IF NOT EXISTS "idx_evaluation_practice" ON "t_evaluation" ("PROFESSIONAL_PRACTICE_ID");

CREATE INDEX IF NOT EXISTS "idx_evaluation_type" ON "t_evaluation" ("EVALUATOR_TYPE");



-- t_evaluation_criteria

CREATE INDEX IF NOT EXISTS "idx_criteria_type" ON "t_evaluation_criteria" ("EVALUATOR_TYPE");



-- t_evaluation_detail

CREATE INDEX IF NOT EXISTS "idx_evaluation_detail_eval" ON "t_evaluation_detail" ("EVALUATION_ID");



-- t_notifications

CREATE INDEX IF NOT EXISTS "idx_notifications_user" ON "t_notifications" ("USER_ID");

CREATE INDEX IF NOT EXISTS "idx_notifications_read" ON "t_notifications" ("USER_ID", "READ");

CREATE INDEX IF NOT EXISTS "idx_notifications_created" ON "t_notifications" ("CREATED_AT" DESC);



-- t_student_documents

CREATE INDEX IF NOT EXISTS "idx_documents_student" ON "t_student_documents" ("STUDENT_ID");

CREATE INDEX IF NOT EXISTS "idx_documents_type" ON "t_student_documents" ("DOCUMENT_TYPE");

CREATE INDEX IF NOT EXISTS "idx_documents_status" ON "t_student_documents" ("STATUS");



-- t_student_requests

CREATE INDEX IF NOT EXISTS "idx_student_requests_student" ON "t_student_requests" ("STUDENT_ID");

CREATE INDEX IF NOT EXISTS "idx_student_requests_status" ON "t_student_requests" ("STATUS");

CREATE INDEX IF NOT EXISTS "idx_student_requests_type" ON "t_student_requests" ("REQUEST_TYPE_ID");

CREATE INDEX IF NOT EXISTS "idx_requests_is_reassignment" ON "t_student_requests" ("IS_REASSIGNMENT");



-- t_request_types

CREATE INDEX IF NOT EXISTS "idx_request_types_category" ON "t_request_types" ("CATEGORY");



-- t_chat_sessions

CREATE INDEX IF NOT EXISTS "idx_chat_sessions_user" ON "t_chat_sessions" ("USER_ID", "STATUS");

CREATE INDEX IF NOT EXISTS "idx_chat_sessions_updated" ON "t_chat_sessions" ("UPDATED_AT" DESC);



-- t_landing_config

CREATE INDEX IF NOT EXISTS "idx_landing_config_key" ON "t_landing_config" ("config_key");



-- t_practice_culmination

CREATE INDEX IF NOT EXISTS "idx_culmination_status" ON "t_practice_culmination" ("STATUS");

CREATE INDEX IF NOT EXISTS "idx_culmination_certificate" ON "t_practice_culmination" ("CERTIFICATE_NUMBER");



-- ============================================================

-- REFERENCE DATA

-- ============================================================



-- t_config (system configuration defaults)





-- t_roles





-- t_user (default admin user - password: admin123)





-- t_user_key (admin password hash)





-- t_user_roles




-- t_internship_type (internship type catalog)







-- t_career (university careers)







-- t_career_internship_type








-- t_internships_period








-- t_list (system list definitions for dropdowns/selectors)























-- t_value_list (system list values)






















































-- t_landing_config (landing page default content)








-- ============================================================

-- t_prospect_lists (prospect lists for internship prospecting)

-- ============================================================

CREATE TABLE IF NOT EXISTS "t_prospect_lists" (

  "LIST_ID" SERIAL NOT NULL,

  "NAME" VARCHAR(255) NOT NULL,

  "DESCRIPTION" TEXT,

  "PERIOD_ID" INTEGER NOT NULL,

  "STATUS" SMALLINT NOT NULL DEFAULT 1,

  "CREATED_AT" TIMESTAMP NOT NULL DEFAULT NOW(),

  "UPDATED_AT" TIMESTAMP NOT NULL DEFAULT NOW(),

  "CREATED_BY" INTEGER,

  PRIMARY KEY ("LIST_ID")

);



ALTER TABLE "t_prospect_lists"

  ADD CONSTRAINT "fk_prospect_lists_period"

  FOREIGN KEY ("PERIOD_ID") REFERENCES "t_internships_period" ("PERIOD_ID");



ALTER TABLE "t_prospect_lists"

  ADD CONSTRAINT "fk_prospect_lists_user"

  FOREIGN KEY ("CREATED_BY") REFERENCES "t_user" ("USER_ID");



-- t_prospect_list_items (students in a prospect list)

CREATE TABLE IF NOT EXISTS "t_prospect_list_items" (

  "ITEM_ID" SERIAL NOT NULL,

  "LIST_ID" INTEGER NOT NULL,

  "STUDENTS_ID" INTEGER NOT NULL,

  "ENROLLED" BOOLEAN NOT NULL DEFAULT FALSE,

  "NOTES" TEXT,

  "ADDED_AT" TIMESTAMP NOT NULL DEFAULT NOW(),

  "ADDED_BY" INTEGER,

  PRIMARY KEY ("ITEM_ID")

);



ALTER TABLE "t_prospect_list_items"

  ADD CONSTRAINT "fk_prospect_items_list"

  FOREIGN KEY ("LIST_ID") REFERENCES "t_prospect_lists" ("LIST_ID") ON DELETE CASCADE;



ALTER TABLE "t_prospect_list_items"

  ADD CONSTRAINT "fk_prospect_items_student"

  FOREIGN KEY ("STUDENTS_ID") REFERENCES "t_students" ("STUDENTS_ID");



ALTER TABLE "t_prospect_list_items"

  ADD CONSTRAINT "fk_prospect_items_user"

  FOREIGN KEY ("ADDED_BY") REFERENCES "t_user" ("USER_ID");



ALTER TABLE "t_prospect_list_items"

  ADD CONSTRAINT "uq_prospect_list_student"

  UNIQUE ("LIST_ID", "STUDENTS_ID");



COMMIT;

