CREATE TABLE IF NOT EXISTS "t_user_sessions" (
  "ID" SERIAL NOT NULL,
  "USER_ID" INTEGER NOT NULL REFERENCES "t_user"("USER_ID"),
  "TOKEN_HASH" VARCHAR(64) NOT NULL,
  "DEVICE_INFO" TEXT,
  "IP_ADDRESS" VARCHAR(45),
  "LAST_ACTIVITY" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "CREATED_AT" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "STATUS" SMALLINT DEFAULT 1,
  PRIMARY KEY ("ID")
);
CREATE INDEX IF NOT EXISTS "idx_user_sessions_user" ON "t_user_sessions"("USER_ID");
