CREATE TABLE IF NOT EXISTS "t_user_notification_prefs" (
  "ID" SERIAL NOT NULL,
  "USER_ID" INTEGER NOT NULL REFERENCES "t_user"("USER_ID"),
  "TYPE" VARCHAR(30) NOT NULL,
  "CHANNEL" VARCHAR(10) NOT NULL,
  "ENABLED" BOOLEAN DEFAULT TRUE,
  "CREATED_AT" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("ID"),
  UNIQUE ("USER_ID", "TYPE", "CHANNEL")
);
