/** Single source of truth for institutional branding */
export const INSTITUTION = {
  legalName: 'UNIVERSIDAD NACIONAL EXPERIMENTAL POLITÉCNICA DE LA FUERZA ARMADA NACIONAL BOLIVARIANA',
  acronym: 'UNEFA',
  headerLines: [
    'REPÚBLICA BOLIVARIANA DE VENEZUELA',
    'MINISTERIO DEL PODER POPULAR PARA LA DEFENSA',
    'UNIVERSIDAD NACIONAL EXPERIMENTAL POLITÉCNICA',
    'DE LA FUERZA ARMADA NACIONAL BOLIVARIANA',
    'VICERRECTORADO DE LA REGIÓN LOS LLANOS',
    'NÚCLEO PORTUGUESA EXTENSIÓN ACARIGUA',
    'EQUIPO DE TRABAJO DE PRÁCTICAS PROFESIONALES',
  ],
} as const;
